##Machile Learning Training Model 
Loading a prebuilt dataset, building a neural network machine learning model that classifies images, training the neural network and evaluating the accuracy of the model.

In [1]:
import tensorflow as tf 
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0,2),
    tf.keras.layers.Dense(10)
])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.09091309, -0.04360475,  0.26475254, -0.66131634,  0.08815846,
         1.3488001 , -0.08289661,  0.13114026,  0.16946177, -1.2001619 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.08858383, 0.07743444, 0.10540277, 0.04175086, 0.08834016,
        0.31163618, 0.0744509 , 0.09221996, 0.09582256, 0.02435834]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

1.1659188

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2585 - accuracy: 0.9271
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1154 - accuracy: 0.9663
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0786 - accuracy: 0.9765
Epoch 4/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0592 - accuracy: 0.9820
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0460 - accuracy: 0.9858


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 2s - loss: 0.0803 - accuracy: 0.9737 - 2s/epoch - 7ms/step


[0.08030527085065842, 0.9736999869346619]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.50397023e-09, 3.53463120e-10, 4.02235941e-07, 2.63119058e-04,
        5.65774545e-11, 7.08803638e-09, 3.22300475e-14, 9.99735653e-01,
        1.46640655e-08, 8.29432906e-07],
       [1.07981124e-09, 2.57997954e-06, 9.99997139e-01, 3.08978258e-07,
        4.90694020e-13, 9.62232072e-10, 4.38746366e-11, 6.66233832e-14,
        1.03871631e-08, 1.93279678e-13],
       [1.61400578e-06, 9.98446286e-01, 4.52786480e-04, 1.10847461e-04,
        1.10652636e-05, 6.73904287e-05, 1.90783721e-05, 3.65434884e-04,
        5.23052120e-04, 2.40493500e-06],
       [9.99987602e-01, 5.73201773e-12, 1.08013583e-05, 5.60215305e-08,
        3.09310355e-10, 1.49291481e-07, 7.95216781e-09, 1.26643511e-06,
        4.14346085e-10, 1.40562221e-07],
       [1.89479579e-05, 3.00753505e-10, 2.29827219e-05, 7.49044716e-07,
        9.96456921e-01, 3.82934324e-08, 7.32831040e-06, 3.19353858e-05,
        5.57430303e-06, 3.45551083e-03]], dtype=float32)>